##!/bin/b.sh 0.5 0.01

sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/0 submit_single_hparam_mosei_emotions.sh  0
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/1 submit_single_hparam_mosei_emotions.sh  1
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/2 submit_single_hparam_mosei_emotions.sh  2
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/3 submit_single_hparam_mosei_emotions.sh  3
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/4 submit_single_hparam_mosei_emotions.sh  4
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/5 submit_single_hparam_mosei_emotions.sh  5
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/6 submit_single_hparam_mosei_emotions.sh  6
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/7 submit_single_hparam_mosei_emotions.sh  7
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/8 submit_single_hparam_mosei_emotions.sh  8
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/9 submit_single_hparam_mosei_emotions.sh  9
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/10 submit_single_hparam_mosei_emotions.sh  10
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/11 submit_single_hparam_mosei_emotions.sh  11
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/12 submit_single_hparam_mosei_emotions.sh  12
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/13 submit_single_hparam_mosei_emotions.sh  13
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/14 submit_single_hparam_mosei_emotions.sh  14
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/15 submit_single_hparam_mosei_emotions.sh  15
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/16 submit_single_hparam_mosei_emotions.sh  16
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/17 submit_single_hparam_mosei_emotions.sh  17
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/18 submit_single_hparam_mosei_emotions.sh  18
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/19 submit_single_hparam_mosei_emotions.sh  19
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/20 submit_single_hparam_mosei_emotions.sh  20
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/21 submit_single_hparam_mosei_emotions.sh  21
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/22 submit_single_hparam_mosei_emotions.sh  22
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/23 submit_single_hparam_mosei_emotions.sh  23
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/24 submit_single_hparam_mosei_emotions.sh  24
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/25 submit_single_hparam_mosei_emotions.sh  25
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/26 submit_single_hparam_mosei_emotions.sh  26
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/27 submit_single_hparam_mosei_emotions.sh  27
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/28 submit_single_hparam_mosei_emotions.sh  28
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/29 submit_single_hparam_mosei_emotions.sh  29
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/30 submit_single_hparam_mosei_emotions.sh  30
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/31 submit_single_hparam_mosei_emotions.sh  31
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/32 submit_single_hparam_mosei_emotions.sh  32
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/33 submit_single_hparam_mosei_emotions.sh  33
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/34 submit_single_hparam_mosei_emotions.sh  34
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/35 submit_single_hparam_mosei_emotions.sh  35
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/36 submit_single_hparam_mosei_emotions.sh  36
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/37 submit_single_hparam_mosei_emotions.sh  37
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/38 submit_single_hparam_mosei_emotions.sh  38
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/39 submit_single_hparam_mosei_emotions.sh  39
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/40 submit_single_hparam_mosei_emotions.sh  40
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/41 submit_single_hparam_mosei_emotions.sh  41
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/42 submit_single_hparam_mosei_emotions.sh  42
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/43 submit_single_hparam_mosei_emotions.sh  43
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/44 submit_single_hparam_mosei_emotions.sh  44
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/45 submit_single_hparam_mosei_emotions.sh  45
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/46 submit_single_hparam_mosei_emotions.sh  46
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/47 submit_single_hparam_mosei_emotions.sh  47
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/48 submit_single_hparam_mosei_emotions.sh  48
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/49 submit_single_hparam_mosei_emotions.sh  49
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/50 submit_single_hparam_mosei_emotions.sh  50
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/51 submit_single_hparam_mosei_emotions.sh  51
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/52 submit_single_hparam_mosei_emotions.sh  52
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/53 submit_single_hparam_mosei_emotions.sh  53
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/54 submit_single_hparam_mosei_emotions.sh  54
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/55 submit_single_hparam_mosei_emotions.sh  55
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/56 submit_single_hparam_mosei_emotions.sh  56
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/57 submit_single_hparam_mosei_emotions.sh  57
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/58 submit_single_hparam_mosei_emotions.sh  58
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/59 submit_single_hparam_mosei_emotions.sh  59
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/60 submit_single_hparam_mosei_emotions.sh  60
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/61 submit_single_hparam_mosei_emotions.sh  61
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/62 submit_single_hparam_mosei_emotions.sh  62
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/63 submit_single_hparam_mosei_emotions.sh  63
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/64 submit_single_hparam_mosei_emotions.sh  64
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/65 submit_single_hparam_mosei_emotions.sh  65
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/66 submit_single_hparam_mosei_emotions.sh  66
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/67 submit_single_hparam_mosei_emotions.sh  67
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/68 submit_single_hparam_mosei_emotions.sh  68
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/69 submit_single_hparam_mosei_emotions.sh  69
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/70 submit_single_hparam_mosei_emotions.sh  70
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/71 submit_single_hparam_mosei_emotions.sh  71
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/72 submit_single_hparam_mosei_emotions.sh  72
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/73 submit_single_hparam_mosei_emotions.sh  73
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/74 submit_single_hparam_mosei_emotions.sh  74
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/75 submit_single_hparam_mosei_emotions.sh  75
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/76 submit_single_hparam_mosei_emotions.sh  76
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/77 submit_single_hparam_mosei_emotions.sh  77
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/78 submit_single_hparam_mosei_emotions.sh  78
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/79 submit_single_hparam_mosei_emotions.sh  79
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/80 submit_single_hparam_mosei_emotions.sh  80
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/81 submit_single_hparam_mosei_emotions.sh  81
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/82 submit_single_hparam_mosei_emotions.sh  82
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/83 submit_single_hparam_mosei_emotions.sh  83
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/84 submit_single_hparam_mosei_emotions.sh  84
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/85 submit_single_hparam_mosei_emotions.sh  85
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/86 submit_single_hparam_mosei_emotions.sh  86
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/87 submit_single_hparam_mosei_emotions.sh  87
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/88 submit_single_hparam_mosei_emotions.sh  88
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/89 submit_single_hparam_mosei_emotions.sh  89
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/90 submit_single_hparam_mosei_emotions.sh  90
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/91 submit_single_hparam_mosei_emotions.sh  91
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/92 submit_single_hparam_mosei_emotions.sh  92
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/93 submit_single_hparam_mosei_emotions.sh  93
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/94 submit_single_hparam_mosei_emotions.sh  94
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/95 submit_single_hparam_mosei_emotions.sh  95
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/96 submit_single_hparam_mosei_emotions.sh  96
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/97 submit_single_hparam_mosei_emotions.sh  97
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/98 submit_single_hparam_mosei_emotions.sh  98
sbatch -p gpu_high --gres=gpu:1 --mem=20G -o log/gridsearch_mosei_emotions/phantomICL/99 submit_single_hparam_mosei_emotions.sh  99
